// AUTO-GENERATED FILE. Do not edit by hand.
// Generated by scripts/build-content.mjs
export const expandedBlogPosts = [
  {
    "id": "rump-roll-delicatessen-opens-dayton",
    "title": "Rump & Roll Delicatessen Opens in Dayton, KY",
    "excerpt": "A new artisan butcher and delicatessen has opened in Dayton, Kentucky, bringing house-made meats and gourmet specialties to the Northern Kentucky community.",
    "category": "news",
    "date": "2025-10-01T00:00:00.000Z",
    "readTime": "3 min read",
    "tags": [
      "Local Business",
      "Dayton KY",
      "Delicatessen",
      "Community",
      "Food & Dining"
    ],
    "featured": true,
    "slug": "rump-roll-delicatessen-opens-dayton",
    "image": "/blog/news/rump-roll-delicatessen-opens-dayton.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2025-10-01T00:00:00.000Z",
    "modifiedDate": "2025-10-01T00:00:00.000Z"
  },
  {
    "id": "drone-footage-real-estate",
    "title": "Drone Footage: How Aerial Shots Elevate Real Estate Marketing",
    "excerpt": "Discover how drone footage transforms real estate marketing by showcasing properties from unique perspectives that drive faster sales and higher prices.",
    "category": "media",
    "date": "2025-9-25",
    "readTime": "7 min read",
    "tags": [
      "Drone Photography",
      "Real Estate Marketing",
      "Aerial Video",
      "Property Marketing"
    ],
    "featured": false,
    "slug": "drone-footage-real-estate",
    "image": "/blog/media/drone-footage-real-estate.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2025-9-25",
    "modifiedDate": "2025-9-25"
  },
  {
    "id": "cincinnati-small-business-growth",
    "title": "Cincinnati Small Business Growth: 2024 Year in Review",
    "excerpt": "A comprehensive look at how Cincinnati small businesses grew in 2024 and what trends will shape the local business landscape in 2025.",
    "category": "news",
    "date": "2024-12-20T00:00:00.000Z",
    "readTime": "6 min read",
    "tags": [
      "Cincinnati Business",
      "Small Business Growth",
      "2024 Review",
      "Local Economy"
    ],
    "featured": false,
    "slug": "cincinnati-small-business-growth",
    "image": "/blog/news/cincinnati-small-business-growth.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-20T00:00:00.000Z",
    "modifiedDate": "2024-12-20T00:00:00.000Z"
  },
  {
    "id": "restaurant-digital-marketing",
    "title": "Complete Digital Marketing Guide for Restaurants in 2025",
    "excerpt": "From Google My Business optimization to social media marketing, discover how restaurants can attract more customers and increase revenue through digital marketing.",
    "category": "marketing",
    "date": "2024-12-18T00:00:00.000Z",
    "readTime": "9 min read",
    "tags": [
      "Restaurant Marketing",
      "Local SEO",
      "Social Media",
      "Google My Business"
    ],
    "featured": false,
    "slug": "restaurant-digital-marketing",
    "image": "/blog/marketing/restaurant-digital-marketing.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-18T00:00:00.000Z",
    "modifiedDate": "2024-12-18T00:00:00.000Z"
  },
  {
    "id": "seo-law-firms",
    "title": "SEO for Law Firms | Best SEO Marketing Strategies",
    "excerpt": "Discover proven SEO strategies that help law firms dominate local search results and attract high-value clients through strategic optimization.",
    "category": "marketing",
    "date": "2024-12-15T00:00:00.000Z",
    "readTime": "8 min read",
    "tags": [
      "SEO",
      "Law Firms",
      "Local SEO",
      "Legal Marketing"
    ],
    "featured": true,
    "slug": "seo-law-firms",
    "image": "/blog/marketing/seo-law-firms.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-15T00:00:00.000Z",
    "modifiedDate": "2024-12-15T00:00:00.000Z"
  },
  {
    "id": "web-design-2025",
    "title": "Best Practices for Small Business Web Design in 2025",
    "excerpt": "Essential web design principles that help small businesses create professional, conversion-focused websites that drive growth and customer engagement.",
    "category": "design",
    "date": "2024-12-12T00:00:00.000Z",
    "readTime": "9 min read",
    "tags": [
      "Web Design",
      "Small Business",
      "UX/UI",
      "2025 Trends"
    ],
    "featured": true,
    "slug": "web-design-2025",
    "image": "/blog/design/web-design-2025.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-12T00:00:00.000Z",
    "modifiedDate": "2024-12-12T00:00:00.000Z"
  },
  {
    "id": "email-marketing-automation",
    "title": "Email Marketing Automation: Complete Guide for Small Businesses",
    "excerpt": "Master email marketing automation to nurture leads, increase conversions, and build lasting customer relationships with strategic automated campaigns.",
    "category": "marketing",
    "date": "2024-12-11T00:00:00.000Z",
    "readTime": "11 min read",
    "tags": [
      "Email Marketing",
      "Automation",
      "Lead Nurturing",
      "Small Business"
    ],
    "featured": false,
    "slug": "email-marketing-automation",
    "image": "/blog/marketing/email-marketing-automation.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-11T00:00:00.000Z",
    "modifiedDate": "2024-12-11T00:00:00.000Z"
  },
  {
    "id": "plastic-surgery-marketing",
    "title": "Plastic Surgery Marketing | Proven SEO & Advertising Strategies",
    "excerpt": "Learn how plastic surgeons can leverage SEO, PPC, and content marketing to build trust and attract qualified patients in a competitive market.",
    "category": "marketing",
    "date": "2024-12-10T00:00:00.000Z",
    "readTime": "10 min read",
    "tags": [
      "Medical Marketing",
      "PPC",
      "SEO",
      "Healthcare"
    ],
    "featured": false,
    "slug": "plastic-surgery-marketing",
    "image": "/blog/marketing/plastic-surgery-marketing.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-10T00:00:00.000Z",
    "modifiedDate": "2024-12-10T00:00:00.000Z"
  },
  {
    "id": "social-media-roi",
    "title": "Measuring Social Media ROI: Complete Guide for Business Success",
    "excerpt": "Learn how to accurately measure social media return on investment with proven strategies that demonstrate real business value and guide optimization decisions.",
    "category": "marketing",
    "date": "2024-12-10T00:00:00.000Z",
    "readTime": "13 min read",
    "tags": [
      "Social Media",
      "ROI",
      "Analytics",
      "Business Growth"
    ],
    "featured": false,
    "slug": "social-media-roi",
    "image": "/blog/marketing/social-media-roi.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-10T00:00:00.000Z",
    "modifiedDate": "2024-12-10T00:00:00.000Z"
  },
  {
    "id": "ppc-small-business",
    "title": "PPC Advertising for Small Businesses: Maximize ROI on Limited Budgets",
    "excerpt": "Learn how small businesses can compete with larger companies through strategic PPC advertising that maximizes every dollar spent.",
    "category": "marketing",
    "date": "2024-12-08T00:00:00.000Z",
    "readTime": "9 min read",
    "tags": [
      "PPC",
      "Google Ads",
      "Small Business",
      "ROI"
    ],
    "featured": false,
    "slug": "ppc-small-business",
    "image": "/blog/marketing/ppc-small-business.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-08T00:00:00.000Z",
    "modifiedDate": "2024-12-08T00:00:00.000Z"
  },
  {
    "id": "local-seo-construction",
    "title": "How Local SEO Drives Leads for Construction Companies",
    "excerpt": "Construction companies can dominate local search with targeted SEO strategies that connect them with homeowners and businesses needing their services.",
    "category": "marketing",
    "date": "2024-12-05T00:00:00.000Z",
    "readTime": "7 min read",
    "tags": [
      "Local SEO",
      "Construction",
      "Lead Generation"
    ],
    "featured": false,
    "slug": "local-seo-construction",
    "image": "/blog/marketing/local-seo-construction.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-05T00:00:00.000Z",
    "modifiedDate": "2024-12-05T00:00:00.000Z"
  },
  {
    "id": "content-marketing-strategy",
    "title": "Content Marketing Strategy That Drives Organic Traffic",
    "excerpt": "Build a content marketing strategy that attracts qualified leads, establishes authority, and drives sustainable organic traffic growth.",
    "category": "marketing",
    "date": "2024-12-03T00:00:00.000Z",
    "readTime": "11 min read",
    "tags": [
      "Content Marketing",
      "SEO",
      "Organic Traffic",
      "Strategy"
    ],
    "featured": false,
    "slug": "content-marketing-strategy",
    "image": "/blog/marketing/content-marketing-strategy.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-12-03T00:00:00.000Z",
    "modifiedDate": "2024-12-03T00:00:00.000Z"
  },
  {
    "id": "testimonial-videos-roi",
    "title": "The ROI of Testimonial Videos for Service Businesses",
    "excerpt": "Discover how testimonial videos generate measurable returns for service businesses through increased trust, higher conversion rates, and improved sales cycles.",
    "category": "media",
    "date": "2024-11-28T00:00:00.000Z",
    "readTime": "8 min read",
    "tags": [
      "Video Marketing",
      "Testimonials",
      "ROI",
      "Service Business"
    ],
    "featured": false,
    "slug": "testimonial-videos-roi",
    "image": "/blog/media/testimonial-videos-roi.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-28T00:00:00.000Z",
    "modifiedDate": "2024-11-28T00:00:00.000Z"
  },
  {
    "id": "video-marketing-trends-2025",
    "title": "Video Marketing Trends 2025: What Businesses Need to Know",
    "excerpt": "Stay ahead of the competition with the latest video marketing trends that will dominate 2025 and transform how businesses connect with customers.",
    "category": "media",
    "date": "2024-11-22T00:00:00.000Z",
    "readTime": "9 min read",
    "tags": [
      "Video Marketing",
      "2025 Trends",
      "Digital Marketing",
      "Business Strategy"
    ],
    "featured": true,
    "slug": "video-marketing-trends-2025",
    "image": "/blog/media/video-marketing-trends-2025.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-22T00:00:00.000Z",
    "modifiedDate": "2024-11-22T00:00:00.000Z"
  },
  {
    "id": "professional-photography-business",
    "title": "Professional Photography: Why Your Business Needs High-Quality Images",
    "excerpt": "Discover how professional photography transforms business marketing by building credibility, increasing engagement, and driving higher conversion rates.",
    "category": "media",
    "date": "2024-11-20T00:00:00.000Z",
    "readTime": "7 min read",
    "tags": [
      "Professional Photography",
      "Business Marketing",
      "Visual Content",
      "Brand Image"
    ],
    "featured": false,
    "slug": "professional-photography-business",
    "image": "/blog/media/professional-photography-business.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-20T00:00:00.000Z",
    "modifiedDate": "2024-11-20T00:00:00.000Z"
  },
  {
    "id": "live-streaming-business",
    "title": "Live Streaming for Business: Engage Customers in Real-Time",
    "excerpt": "Learn how live streaming transforms business marketing by creating authentic connections, driving immediate engagement, and building stronger customer relationships.",
    "category": "media",
    "date": "2024-11-18T00:00:00.000Z",
    "readTime": "8 min read",
    "tags": [
      "Live Streaming",
      "Real-Time Marketing",
      "Customer Engagement",
      "Digital Strategy"
    ],
    "featured": false,
    "slug": "live-streaming-business",
    "image": "/blog/media/live-streaming-business.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-18T00:00:00.000Z",
    "modifiedDate": "2024-11-18T00:00:00.000Z"
  },
  {
    "id": "podcast-marketing",
    "title": "Podcast Marketing: How to Build Authority and Attract Customers",
    "excerpt": "Discover how podcast marketing builds business authority, attracts qualified customers, and creates lasting relationships through authentic audio content.",
    "category": "media",
    "date": "2024-11-16T00:00:00.000Z",
    "readTime": "9 min read",
    "tags": [
      "Podcast Marketing",
      "Authority Building",
      "Content Strategy",
      "Customer Acquisition"
    ],
    "featured": false,
    "slug": "podcast-marketing",
    "image": "/blog/media/podcast-marketing.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-16T00:00:00.000Z",
    "modifiedDate": "2024-11-16T00:00:00.000Z"
  },
  {
    "id": "brand-design-conversion-rates",
    "title": "How Brand Design Impacts Conversion Rates",
    "excerpt": "Discover how strategic brand design elements directly influence customer behavior and conversion rates through psychological principles and visual communication.",
    "category": "design",
    "date": "2024-11-14T00:00:00.000Z",
    "readTime": "8 min read",
    "tags": [
      "Brand Design",
      "Conversion Optimization",
      "Psychology",
      "Business Growth"
    ],
    "featured": false,
    "slug": "brand-design-conversion-rates",
    "image": "/blog/design/brand-design-conversion-rates.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-14T00:00:00.000Z",
    "modifiedDate": "2024-11-14T00:00:00.000Z"
  },
  {
    "id": "mobile-first-design",
    "title": "Mobile-First Design: Why Your Website Must Prioritize Mobile Users",
    "excerpt": "Learn why mobile-first design is essential for business success and how to create websites that excel on mobile devices while enhancing desktop experiences.",
    "category": "design",
    "date": "2024-11-12T00:00:00.000Z",
    "readTime": "8 min read",
    "tags": [
      "Mobile Design",
      "Responsive Design",
      "User Experience",
      "Web Development"
    ],
    "featured": false,
    "slug": "mobile-first-design",
    "image": "/blog/design/mobile-first-design.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-12T00:00:00.000Z",
    "modifiedDate": "2024-11-12T00:00:00.000Z"
  },
  {
    "id": "logo-design-psychology",
    "title": "Logo Design Psychology: How Colors and Shapes Influence Customers",
    "excerpt": "Discover how strategic logo design elements including colors, shapes, and typography influence customer perceptions and purchasing decisions through psychological principles.",
    "category": "design",
    "date": "2024-11-10T00:00:00.000Z",
    "readTime": "9 min read",
    "tags": [
      "Logo Design",
      "Brand Psychology",
      "Color Psychology",
      "Visual Identity"
    ],
    "featured": false,
    "slug": "logo-design-psychology",
    "image": "/blog/design/logo-design-psychology.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-10T00:00:00.000Z",
    "modifiedDate": "2024-11-10T00:00:00.000Z"
  },
  {
    "id": "ecommerce-design-elements",
    "title": "E-commerce Design Elements That Drive Sales and Conversions",
    "excerpt": "Discover the essential e-commerce design elements that increase sales and conversions through strategic layout, psychology, and user experience optimization.",
    "category": "design",
    "date": "2024-11-08T00:00:00.000Z",
    "readTime": "10 min read",
    "tags": [
      "E-commerce Design",
      "Conversion Optimization",
      "User Experience",
      "Online Sales"
    ],
    "featured": false,
    "slug": "ecommerce-design-elements",
    "image": "/blog/design/ecommerce-design-elements.jpg",
    "author": "Uptrade Media Team",
    "publishDate": "2024-11-08T00:00:00.000Z",
    "modifiedDate": "2024-11-08T00:00:00.000Z"
  }
];
